const categoryPresetNames = <String, Map<String, String>>{
  'food': {
    'en': 'Food & drinks',
    'fr': 'Repas et boissons',
    'mg': 'Sakafo sy zava-pisotro',
    'de': 'Essen & Trinken',
    'es': 'Comida y bebida',
    'it': 'Cibo e bevande',
  },
  'shopping': {
    'en': 'Groceries',
    'fr': 'Courses',
    'mg': 'Fiantsenana',
    'de': 'Lebensmittel',
    'es': 'Compras',
    'it': 'Spesa',
  },
  'transport': {
    'en': 'Transport',
    'fr': 'Transport',
    'mg': 'Fitaterana',
    'de': 'Transport',
    'es': 'Transporte',
    'it': 'Trasporti',
  },
  'health': {
    'en': 'Health',
    'fr': 'Santé',
    'mg': 'Fahasalamana',
    'de': 'Gesundheit',
    'es': 'Salud',
    'it': 'Salute',
  },
  'utilities': {
    'en': 'Utilities',
    'fr': 'Charges',
    'mg': 'Jiro sy rano',
    'de': 'Nebenkosten',
    'es': 'Servicios',
    'it': 'Utenze',
  },
  'entertainment': {
    'en': 'Entertainment',
    'fr': 'Divertissement',
    'mg': 'Fialam-boly',
    'de': 'Unterhaltung',
    'es': 'Entretenimiento',
    'it': 'Intrattenimento',
  },
  'salary': {
    'en': 'Salary',
    'fr': 'Salaire',
    'mg': 'Karama',
    'de': 'Gehalt',
    'es': 'Salario',
    'it': 'Stipendio',
  },
  'freelance': {
    'en': 'Side-hustle',
    'fr': 'Activité secondaire',
    'mg': 'Asa fanampiny',
    'de': 'Nebenjob',
    'es': 'Trabajo extra',
    'it': 'Lavoro extra',
  },
};
